name: nomisal_res
description: An application to integrate dart backend in nomisal style
version: 0.0.2
repository: https://github.com/nomagicisreal/nomisal_res

environment:
  sdk: ^3.7.2

dependencies:
  damath: ^0.0.38
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
